name: Deploy Prod
on:
  create:
    tags:
      - v*
jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    - name: Install NPM dependencies
      run: |
        cd api
        npm install
    - name: build project
      run: |
        cd api
        make clean build 
    - name: deploy
      env:
        GIT_PAT: ${{ secrets.PROD_GIT_PAT }}
        AUTH: ${{ secrets.MONGO_CERT }}
      run: |
        cd api
        echo "$AUTH" | base64 --decode > ./util/mongo_cert.pem
        sls deploy -s prod
