name: Deploy Prod
on:
  create:
    tags:
      - v*
jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    - name: Install NPM dependencies
      run: |
        cd api
        npm install
    - name: build project
      run: |
        cd api
        make clean build 
    - name: deploy
      env:
        GIT_PAT_0: ${{ secrets.PROD_GIT_PAT_00 }}
        GIT_PAT_1: ${{ secrets.PROD_GIT_PAT_01 }}
        GIT_PAT_2: ${{ secrets.PROD_GIT_PAT_02 }}
        GIT_PAT_3: ${{ secrets.PROD_GIT_PAT_03 }}
        GIT_PAT_4: ${{ secrets.PROD_GIT_PAT_04 }}
        GIT_PAT_5: ${{ secrets.PROD_GIT_PAT_05 }}
        GIT_PAT_6: ${{ secrets.PROD_GIT_PAT_06 }}
        GIT_PAT_7: ${{ secrets.PROD_GIT_PAT_07 }}
        GIT_PAT_8: ${{ secrets.PROD_GIT_PAT_08 }}
        GIT_PAT_9: ${{ secrets.PROD_GIT_PAT_09 }}
        GIT_PAT_10: ${{ secrets.PROD_GIT_PAT_10 }}
        GIT_PAT_11: ${{ secrets.PROD_GIT_PAT_11 }}
        GIT_PAT_12: ${{ secrets.PROD_GIT_PAT_12 }}
        GIT_PAT_13: ${{ secrets.PROD_GIT_PAT_13 }}
        GIT_PAT_14: ${{ secrets.PROD_GIT_PAT_14 }}
        GIT_PAT_15: ${{ secrets.PROD_GIT_PAT_15 }}
        GIT_PAT_16: ${{ secrets.PROD_GIT_PAT_16 }}
        GIT_PAT_17: ${{ secrets.PROD_GIT_PAT_17 }}
        GIT_PAT_18: ${{ secrets.PROD_GIT_PAT_18 }}
        GIT_PAT_19: ${{ secrets.PROD_GIT_PAT_19 }}
        GIT_PAT_20: ${{ secrets.PROD_GIT_PAT_20 }}
        AUTH: ${{ secrets.MONGO_CERT }}
      run: |
        cd api
        echo "$AUTH" | base64 --decode > ./util/mongo_cert.pem
        sls deploy -s prod
