name: Deploy Prod
on:
  push:
    tag:
      - 'v*'
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    - name: Install NPM dependencies
      run: |
        cd api
        npm install
    - name: build project
      run: |
        cd api
        make clean build 
    - name: deploy
      env:
        GIT_PAT_1: ${{ secrets.GIT_PAT_1 }}
        GIT_PAT_2: ${{ secrets.GIT_PAT_2 }}
        GIT_PAT_3: ${{ secrets.GIT_PAT_3 }}
        GIT_PAT_4: ${{ secrets.GIT_PAT_4 }}
        GIT_PAT_5: ${{ secrets.GIT_PAT_5 }}
        GIT_PAT_6: ${{ secrets.GIT_PAT_6 }}
        GIT_PAT_7: ${{ secrets.GIT_PAT_7 }}
        GIT_PAT_8: ${{ secrets.GIT_PAT_8 }}
        GIT_PAT_9: ${{ secrets.GIT_PAT_9 }}
        GIT_PAT_10: ${{ secrets.GIT_PAT_10 }}
        GIT_PAT_11: ${{ secrets.GIT_PAT_11 }}
        GIT_PAT_12: ${{ secrets.GIT_PAT_12 }}
        AUTH: ${{ secrets.MONGO_CERT }}
      run: |
        cd api
        echo "$AUTH" | base64 --decode > ./util/mongo_cert.pem
        sls deploy -s prod