name: Push Container to Heroku

on: 
  push:
    branches:
      - main
      - 67-add-action-to-deploy-to-heroku # TEMP TEMP TEMP

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME}}.git origin/main:main